name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: goanpeca/setup-miniconda@v1.0.2
      with:
           activate-environment: TUM-teaching-sample
           environment-file: environment.yml
           python-version: 3.7
           auto-activate-base: false

    - name: run lecture
      shell: bash -l {0}
      run: |
        export PATH="$PATH:/usr/share/miniconda/bin"
        source .envrc
        flake8-nb; [ $? -eq 0 ] || exit 1
        black-nb --check .; [ $? -eq 0 ] || exit 1

        jupyter nbconvert --to notebook --execute lecture.ipynb

        py.test
